### ISSUE TITLE
[Bug] Dashboard File is Not Loading

### ISSUE THREAD

**Issue by mwang87** [Wang-Bioinformatics-Lab/GNPS_LCMSDashboard#282]
https://dashboard.gnps2.org/?usi=mzspec%3AGNPS%3ATASK-d91c81bb0ebf49fbb68ef6019a2db311-f.mrs97%2FLiquid_footprinting_negative_mode_11_16_2021%2FNegative%20Mode%2FAQNEGMATTHEW20211028_03-QC1.mzML#%7B%7D

**Comment by StelioPapala** [comment]
Trying to open Files in the dashboard, either from the "file summary" of the gnps2 task or by direct upload, gives a "USI1 Loading Error" in the "File Download/Conversion" field of the Loading Statuses part (see picture). ![image](https://github.com/Wang-Bioinformatics-Lab/GNPS_LCMSDashboard/assets/159769198/e9192e11-c9e7-431c-919b-3dfc03b48323)

This problem started occurring on Friday (9th of February), on the day before it worked.


Using a link prepared on Thursday (8th of Feb.) https://dashboard.gnps2.org//?xic_mz=250.1185414&xic_formula=&xic_peptide=&xic_tolerance=0.5&xic_ppm_tolerance=10&xic_tolerance_unit=ppm&xic_rt_window=&xic_norm=False&xic_file_grouping=MZ&xic_integration_type=AUC&show_ms2_markers=True&ms2marker_color=blue&ms2marker_size=5&ms2_identifier=None&show_lcms_2nd_map=False&map_plot_zoom=%7B%7D&polarity_filtering=None&polarity_filtering2=None&tic_option=TIC&overlay_usi=None&overlay_mz=None&overlay_rt=None&overlay_color=&overlay_size=&overlay_hover=&overlay_filter_column=&overlay_filter_value=&feature_finding_type=Off&feature_finding_ppm=10&feature_finding_noise=10000&feature_finding_min_peak_rt=0.05&feature_finding_max_peak_rt=1.5&feature_finding_rt_tolerance=0.3&massql_statement=QUERY+scaninfo%28MS2DATA%29&sychronization_session_id=35d49ed761154287a4632762a64400f6&chromatogram_options=%5B%5D&comment=&map_plot_color_scale=Hot_r&map_plot_quantization_level=Medium&plot_theme=plotly_white#%7B%22usi%22%3A%20%22mzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/SIO_1D-DOM_12.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/SIO_1D-DOM_16.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/SIO_1D-DOM_1.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/SIO_1D-DOM_8.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/Stelio_100_2.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/Stelio_100_3.mzML%5Cnmzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/Std_100_1.mzML%22%2C%20%22usi_select%22%3A%20%22mzspec%3AGNPS2%3ATASK-29014fb3e515464797de16c4b9510141-input_spectra/SIO_1D-DOM_12.mzML%22%2C%20%22usi2%22%3A%20%22%22%7D

it says "File Download/Conversion: Ready" and shows the XIC plot correctly, but changing the desired XIC fails to update the plot.
